export enum PermissionCodes
{
    
    ReadBusinessSystemTier,
	EditBusinessSystemTier,
	InsertBusinessSystemTier,
	DeleteBusinessSystemTier,
	ReadGender,
	EditGender,
	InsertGender,
	DeleteGender,
	ReadSegmentationItem,
	EditSegmentationItem,
	InsertSegmentationItem,
	DeleteSegmentationItem,
	ReadPartnerUserSegmentation,
	EditPartnerUserSegmentation,
	InsertPartnerUserSegmentation,
	DeletePartnerUserSegmentation,
	ReadPartnerUserPartnerNotification,
	EditPartnerUserPartnerNotification,
	InsertPartnerUserPartnerNotification,
	DeletePartnerUserPartnerNotification,
	ReadDiscountProductGroup,
	EditDiscountProductGroup,
	InsertDiscountProductGroup,
	DeleteDiscountProductGroup,
	ReadUserExtended,
	EditUserExtended,
	InsertUserExtended,
	DeleteUserExtended,
	ReadUserNotification,
	EditUserNotification,
	InsertUserNotification,
	DeleteUserNotification,
	ReadTransaction,
	EditTransaction,
	InsertTransaction,
	DeleteTransaction,
	ReadPartnerRole,
	EditPartnerRole,
	InsertPartnerRole,
	DeletePartnerRole,
	ReadPartnerRolePartnerPermission,
	EditPartnerRolePartnerPermission,
	InsertPartnerRolePartnerPermission,
	DeletePartnerRolePartnerPermission,
	ReadPartnerUser,
	EditPartnerUser,
	InsertPartnerUser,
	DeletePartnerUser,
	ReadBusinessSystemTierDiscountProductGroup,
	EditBusinessSystemTierDiscountProductGroup,
	InsertBusinessSystemTierDiscountProductGroup,
	DeleteBusinessSystemTierDiscountProductGroup,
	ReadBusinessSystem,
	EditBusinessSystem,
	InsertBusinessSystem,
	DeleteBusinessSystem,
	ReadPartnerUserPartnerRole,
	EditPartnerUserPartnerRole,
	InsertPartnerUserPartnerRole,
	DeletePartnerUserPartnerRole,
	ReadPartnerNotification,
	EditPartnerNotification,
	InsertPartnerNotification,
	DeletePartnerNotification,
	ReadBusinessSystemUpdatePointsScheduledTask,
	EditBusinessSystemUpdatePointsScheduledTask,
	InsertBusinessSystemUpdatePointsScheduledTask,
	DeleteBusinessSystemUpdatePointsScheduledTask,
	ReadNotification,
	EditNotification,
	InsertNotification,
	DeleteNotification,
	ReadPartner,
	EditPartner,
	InsertPartner,
	DeletePartner,
	ReadPartnerUserSegmentationItem,
	EditPartnerUserSegmentationItem,
	InsertPartnerUserSegmentationItem,
	DeletePartnerUserSegmentationItem,
	ReadPartnerPermission,
	EditPartnerPermission,
	InsertPartnerPermission,
	DeletePartnerPermission,
	ReadTier,
	EditTier,
	InsertTier,
	DeleteTier,
	ReadSegmentation,
	EditSegmentation,
	InsertSegmentation,
	DeleteSegmentation,
	ReadRole,
	EditRole,
	InsertRole,
	DeleteRole
}

export enum PartnerPermissionCodes
{
    ReadPartnerRole = 1,
	EditPartnerRole = 2,
	InsertPartnerRole = 3,
	DeletePartnerRole = 4,
	ReadPartnerUser = 5,
	EditPartnerUser = 6,
	DeletePartnerUser = 7,
	ReadPartnerNotification = 8,
	EditPartnerNotification = 9,
	InsertPartnerNotification = 10,
	DeletePartnerNotification = 11,
	ReadPartner = 12,
	EditPartner = 13,
	ReadTier = 14,
	EditTier = 15,
	InsertTier = 16,
	DeleteTier = 17,
	ReadSegmentation = 18,
	EditSegmentation = 19,
	InsertSegmentation = 20,
	DeleteSegmentation = 21,
    
}

export enum TransactionStatusCodes
{
    Completed = 1,
	Cancelled = 2,
    
}


