// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Playerty.Loyals.Infrastructure;

#nullable disable

namespace Playerty.Loyals.Infrastructure.Migrations
{
    [DbContext(typeof(PLApplicationDbContext))]
    [Migration("20240930003604_InitialCreate")]
    partial class InitialCreate
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.2")
                .HasAnnotation("Proxies:ChangeTracking", false)
                .HasAnnotation("Proxies:CheckEquality", false)
                .HasAnnotation("Proxies:LazyLoading", true)
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("PartnerRolePartnerUser", b =>
                {
                    b.Property<int>("PartnerRolesId")
                        .HasColumnType("int");

                    b.Property<long>("PartnerUsersId")
                        .HasColumnType("bigint");

                    b.HasKey("PartnerRolesId", "PartnerUsersId");

                    b.HasIndex("PartnerUsersId");

                    b.ToTable("PartnerRolePartnerUser");
                });

            modelBuilder.Entity("PermissionRole", b =>
                {
                    b.Property<int>("PermissionsId")
                        .HasColumnType("int");

                    b.Property<int>("RolesId")
                        .HasColumnType("int");

                    b.HasKey("PermissionsId", "RolesId");

                    b.HasIndex("RolesId");

                    b.ToTable("PermissionRole");
                });

            modelBuilder.Entity("Playerty.Loyals.Business.Entities.Gender", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("Name")
                        .HasMaxLength(70)
                        .HasColumnType("nvarchar(70)");

                    b.Property<string>("NameLatin")
                        .HasMaxLength(70)
                        .HasColumnType("nvarchar(70)");

                    b.HasKey("Id");

                    b.ToTable("Gender");
                });

            modelBuilder.Entity("Playerty.Loyals.Business.Entities.Partner", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("LoadPurchasesEndpoint")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("LoadReversalsEndpoint")
                        .HasColumnType("nvarchar(max)");

                    b.Property<byte[]>("LogoImage")
                        .HasColumnType("varbinary(max)");

                    b.Property<DateTime>("ModifiedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<string>("Slug")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<int?>("UpdatePointsInterval")
                        .HasColumnType("int");

                    b.Property<int>("Version")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("Slug")
                        .IsUnique()
                        .HasFilter("[Slug] IS NOT NULL");

                    b.ToTable("Partners");
                });

            modelBuilder.Entity("Playerty.Loyals.Business.Entities.PartnerNotificationPartnerUser", b =>
                {
                    b.Property<long>("PartnerNotificationsId")
                        .HasColumnType("bigint");

                    b.Property<long>("PartnerUsersId")
                        .HasColumnType("bigint");

                    b.Property<bool?>("IsMarkedAsRead")
                        .HasColumnType("bit");

                    b.HasKey("PartnerNotificationsId", "PartnerUsersId");

                    b.HasIndex("PartnerUsersId");

                    b.ToTable("PartnerNotificationPartnerUser");
                });

            modelBuilder.Entity("Playerty.Loyals.Business.Entities.PartnerUserSegmentation", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("Id"));

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<bool>("IsFilledFirstTime")
                        .HasColumnType("bit");

                    b.Property<DateTime>("ModifiedAt")
                        .HasColumnType("datetime2");

                    b.Property<long?>("PartnerUserId")
                        .HasColumnType("bigint");

                    b.Property<int?>("SegmentationId")
                        .HasColumnType("int");

                    b.Property<int>("Version")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("PartnerUserId");

                    b.HasIndex("SegmentationId");

                    b.ToTable("PartnerUserSegmentation");
                });

            modelBuilder.Entity("Playerty.Loyals.Business.Entities.Segmentation", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("Description")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("ModifiedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("Name")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<int>("PointsForFirstTimeFill")
                        .HasColumnType("int");

                    b.Property<int>("Version")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.ToTable("Segmentation");
                });

            modelBuilder.Entity("Playerty.Loyals.Business.Entities.SegmentationItem", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("Id"));

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("ModifiedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("Name")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<int?>("SegmentationId")
                        .HasColumnType("int");

                    b.Property<int>("Version")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("SegmentationId");

                    b.ToTable("SegmentationItem");
                });

            modelBuilder.Entity("Playerty.Loyals.Business.Entities.Tier", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("ModifiedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<string>("NameLatin")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<int?>("PartnerId")
                        .HasColumnType("int");

                    b.Property<int>("ValidFrom")
                        .HasColumnType("int");

                    b.Property<int>("ValidTo")
                        .HasColumnType("int");

                    b.Property<int>("Version")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("PartnerId");

                    b.ToTable("Tiers");
                });

            modelBuilder.Entity("Playerty.Loyals.Business.Entities.Transaction", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("Id"));

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<Guid>("Guid")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("ModifiedAt")
                        .HasColumnType("datetime2");

                    b.Property<int>("Points")
                        .HasColumnType("int");

                    b.Property<decimal>("Price")
                        .HasPrecision(16, 2)
                        .HasColumnType("decimal(16,2)");

                    b.Property<long>("UserId")
                        .HasColumnType("bigint");

                    b.Property<int>("Version")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("Transactions");
                });

            modelBuilder.Entity("Playerty.Loyals.Business.Entities.TransactionProduct", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("Id"));

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<long>("ProductId")
                        .HasColumnType("bigint");

                    b.Property<long>("TransactionId")
                        .HasColumnType("bigint");

                    b.HasKey("Id");

                    b.HasIndex("TransactionId");

                    b.ToTable("TransactionProduct");
                });

            modelBuilder.Entity("Playerty.Loyals.Business.Entities.TransactionStatus", b =>
                {
                    b.Property<byte>("Id")
                        .HasColumnType("tinyint");

                    b.Property<string>("Code")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<string>("NameLatin")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<long?>("TransactionId")
                        .HasColumnType("bigint");

                    b.HasKey("Id");

                    b.HasIndex("TransactionId");

                    b.ToTable("TransactionStatuses");
                });

            modelBuilder.Entity("Playerty.Loyals.Business.Entities.UserExtended", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("Id"));

                    b.Property<DateTime?>("BirthDate")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("Discriminator")
                        .IsRequired()
                        .HasMaxLength(13)
                        .HasColumnType("nvarchar(13)");

                    b.Property<string>("Email")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(70)
                        .HasColumnType("nvarchar(70)");

                    b.Property<int?>("GenderId")
                        .HasColumnType("int");

                    b.Property<bool>("HasLoggedInWithExternalProvider")
                        .HasColumnType("bit");

                    b.Property<DateTime>("ModifiedAt")
                        .HasColumnType("datetime2");

                    b.Property<int>("NumberOfFailedAttemptsInARow")
                        .HasColumnType("int");

                    b.Property<string>("Password")
                        .HasMaxLength(80)
                        .HasColumnType("nvarchar(80)");

                    b.Property<int>("Version")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("Email")
                        .IsUnique();

                    b.HasIndex("GenderId");

                    b.ToTable("Users");

                    b.HasDiscriminator<string>("Discriminator").HasValue("UserExtended");

                    b.UseTphMappingStrategy();
                });

            modelBuilder.Entity("Soft.Generator.Security.Entities.Notification", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("Id"));

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<string>("DescriptionLatin")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<string>("Discriminator")
                        .IsRequired()
                        .HasMaxLength(21)
                        .HasColumnType("nvarchar(21)");

                    b.Property<DateTime>("ModifiedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(60)
                        .HasColumnType("nvarchar(60)");

                    b.Property<string>("TitleLatin")
                        .IsRequired()
                        .HasMaxLength(60)
                        .HasColumnType("nvarchar(60)");

                    b.Property<int>("Version")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.ToTable("Notifications");

                    b.HasDiscriminator<string>("Discriminator").HasValue("Notification");

                    b.UseTphMappingStrategy();
                });

            modelBuilder.Entity("Soft.Generator.Security.Entities.NotificationUser", b =>
                {
                    b.Property<long>("NotificationsId")
                        .HasColumnType("bigint");

                    b.Property<long>("UsersId")
                        .HasColumnType("bigint");

                    b.Property<bool?>("IsMarkedAsRead")
                        .HasColumnType("bit");

                    b.HasKey("NotificationsId", "UsersId");

                    b.HasIndex("UsersId");

                    b.ToTable("NotificationUser");
                });

            modelBuilder.Entity("Soft.Generator.Security.Entities.Permission", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Code")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("Description")
                        .HasMaxLength(400)
                        .HasColumnType("nvarchar(400)");

                    b.Property<string>("DescriptionLatin")
                        .HasMaxLength(400)
                        .HasColumnType("nvarchar(400)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("NameLatin")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.HasKey("Id");

                    b.HasIndex("Code")
                        .IsUnique();

                    b.ToTable("Permissions");
                });

            modelBuilder.Entity("Soft.Generator.Security.Entities.Role", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("Description")
                        .HasMaxLength(400)
                        .HasColumnType("nvarchar(400)");

                    b.Property<string>("Discriminator")
                        .IsRequired()
                        .HasMaxLength(13)
                        .HasColumnType("nvarchar(13)");

                    b.Property<DateTime>("ModifiedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<int>("Version")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.ToTable("Roles");

                    b.HasDiscriminator<string>("Discriminator").HasValue("Role");

                    b.UseTphMappingStrategy();
                });

            modelBuilder.Entity("Soft.Generator.Security.Entities.RoleUser", b =>
                {
                    b.Property<int>("RolesId")
                        .HasColumnType("int");

                    b.Property<long>("UsersId")
                        .HasColumnType("bigint");

                    b.HasKey("RolesId", "UsersId");

                    b.HasIndex("UsersId");

                    b.ToTable("RoleUser");
                });

            modelBuilder.Entity("Playerty.Loyals.Business.Entities.PartnerUser", b =>
                {
                    b.HasBaseType("Playerty.Loyals.Business.Entities.UserExtended");

                    b.Property<int?>("PartnerId")
                        .HasColumnType("int");

                    b.Property<int>("Points")
                        .HasColumnType("int");

                    b.Property<int?>("TierId")
                        .HasColumnType("int");

                    b.HasIndex("PartnerId");

                    b.HasIndex("TierId");

                    b.HasDiscriminator().HasValue("PartnerUser");
                });

            modelBuilder.Entity("Playerty.Loyals.Business.Entities.PartnerNotification", b =>
                {
                    b.HasBaseType("Soft.Generator.Security.Entities.Notification");

                    b.Property<int?>("PartnerId")
                        .HasColumnType("int");

                    b.HasIndex("PartnerId");

                    b.HasDiscriminator().HasValue("PartnerNotification");
                });

            modelBuilder.Entity("Playerty.Loyals.Business.Entities.PartnerRole", b =>
                {
                    b.HasBaseType("Soft.Generator.Security.Entities.Role");

                    b.Property<int?>("PartnerId")
                        .HasColumnType("int");

                    b.HasIndex("PartnerId");

                    b.HasDiscriminator().HasValue("PartnerRole");
                });

            modelBuilder.Entity("PartnerRolePartnerUser", b =>
                {
                    b.HasOne("Playerty.Loyals.Business.Entities.PartnerRole", null)
                        .WithMany()
                        .HasForeignKey("PartnerRolesId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Playerty.Loyals.Business.Entities.PartnerUser", null)
                        .WithMany()
                        .HasForeignKey("PartnerUsersId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("PermissionRole", b =>
                {
                    b.HasOne("Soft.Generator.Security.Entities.Permission", null)
                        .WithMany()
                        .HasForeignKey("PermissionsId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Soft.Generator.Security.Entities.Role", null)
                        .WithMany()
                        .HasForeignKey("RolesId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Playerty.Loyals.Business.Entities.PartnerNotificationPartnerUser", b =>
                {
                    b.HasOne("Playerty.Loyals.Business.Entities.PartnerNotification", null)
                        .WithMany()
                        .HasForeignKey("PartnerNotificationsId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Playerty.Loyals.Business.Entities.PartnerUser", null)
                        .WithMany()
                        .HasForeignKey("PartnerUsersId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Playerty.Loyals.Business.Entities.PartnerUserSegmentation", b =>
                {
                    b.HasOne("Playerty.Loyals.Business.Entities.PartnerUser", "PartnerUser")
                        .WithMany("PartnerUserSegmentations")
                        .HasForeignKey("PartnerUserId");

                    b.HasOne("Playerty.Loyals.Business.Entities.Segmentation", "Segmentation")
                        .WithMany()
                        .HasForeignKey("SegmentationId");

                    b.Navigation("PartnerUser");

                    b.Navigation("Segmentation");
                });

            modelBuilder.Entity("Playerty.Loyals.Business.Entities.SegmentationItem", b =>
                {
                    b.HasOne("Playerty.Loyals.Business.Entities.Segmentation", "Segmentation")
                        .WithMany("SegmentationItems")
                        .HasForeignKey("SegmentationId");

                    b.Navigation("Segmentation");
                });

            modelBuilder.Entity("Playerty.Loyals.Business.Entities.Tier", b =>
                {
                    b.HasOne("Playerty.Loyals.Business.Entities.Partner", "Partner")
                        .WithMany("Tiers")
                        .HasForeignKey("PartnerId");

                    b.Navigation("Partner");
                });

            modelBuilder.Entity("Playerty.Loyals.Business.Entities.Transaction", b =>
                {
                    b.HasOne("Playerty.Loyals.Business.Entities.UserExtended", "User")
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("Playerty.Loyals.Business.Entities.TransactionProduct", b =>
                {
                    b.HasOne("Playerty.Loyals.Business.Entities.Transaction", "Transaction")
                        .WithMany()
                        .HasForeignKey("TransactionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Transaction");
                });

            modelBuilder.Entity("Playerty.Loyals.Business.Entities.TransactionStatus", b =>
                {
                    b.HasOne("Playerty.Loyals.Business.Entities.Transaction", null)
                        .WithMany("Statuses")
                        .HasForeignKey("TransactionId");
                });

            modelBuilder.Entity("Playerty.Loyals.Business.Entities.UserExtended", b =>
                {
                    b.HasOne("Playerty.Loyals.Business.Entities.Gender", "Gender")
                        .WithMany()
                        .HasForeignKey("GenderId");

                    b.Navigation("Gender");
                });

            modelBuilder.Entity("Soft.Generator.Security.Entities.NotificationUser", b =>
                {
                    b.HasOne("Soft.Generator.Security.Entities.Notification", null)
                        .WithMany()
                        .HasForeignKey("NotificationsId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Playerty.Loyals.Business.Entities.UserExtended", null)
                        .WithMany()
                        .HasForeignKey("UsersId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Soft.Generator.Security.Entities.RoleUser", b =>
                {
                    b.HasOne("Soft.Generator.Security.Entities.Role", null)
                        .WithMany()
                        .HasForeignKey("RolesId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Playerty.Loyals.Business.Entities.UserExtended", null)
                        .WithMany()
                        .HasForeignKey("UsersId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Playerty.Loyals.Business.Entities.PartnerUser", b =>
                {
                    b.HasOne("Playerty.Loyals.Business.Entities.Partner", "Partner")
                        .WithMany("Users")
                        .HasForeignKey("PartnerId");

                    b.HasOne("Playerty.Loyals.Business.Entities.Tier", "Tier")
                        .WithMany("PartnerUsers")
                        .HasForeignKey("TierId");

                    b.Navigation("Partner");

                    b.Navigation("Tier");
                });

            modelBuilder.Entity("Playerty.Loyals.Business.Entities.PartnerNotification", b =>
                {
                    b.HasOne("Playerty.Loyals.Business.Entities.Partner", "Partner")
                        .WithMany("PartnerNotifications")
                        .HasForeignKey("PartnerId");

                    b.Navigation("Partner");
                });

            modelBuilder.Entity("Playerty.Loyals.Business.Entities.PartnerRole", b =>
                {
                    b.HasOne("Playerty.Loyals.Business.Entities.Partner", "Partner")
                        .WithMany("PartnerRoles")
                        .HasForeignKey("PartnerId");

                    b.Navigation("Partner");
                });

            modelBuilder.Entity("Playerty.Loyals.Business.Entities.Partner", b =>
                {
                    b.Navigation("PartnerNotifications");

                    b.Navigation("PartnerRoles");

                    b.Navigation("Tiers");

                    b.Navigation("Users");
                });

            modelBuilder.Entity("Playerty.Loyals.Business.Entities.Segmentation", b =>
                {
                    b.Navigation("SegmentationItems");
                });

            modelBuilder.Entity("Playerty.Loyals.Business.Entities.Tier", b =>
                {
                    b.Navigation("PartnerUsers");
                });

            modelBuilder.Entity("Playerty.Loyals.Business.Entities.Transaction", b =>
                {
                    b.Navigation("Statuses");
                });

            modelBuilder.Entity("Playerty.Loyals.Business.Entities.PartnerUser", b =>
                {
                    b.Navigation("PartnerUserSegmentations");
                });
#pragma warning restore 612, 618
        }
    }
}
