// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Playerty.Loyals.Infrastructure;

#nullable disable

namespace Playerty.Loyals.Infrastructure.Migrations
{
    [DbContext(typeof(PLApplicationDbContext))]
    partial class PLApplicationDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.2")
                .HasAnnotation("Proxies:ChangeTracking", false)
                .HasAnnotation("Proxies:CheckEquality", false)
                .HasAnnotation("Proxies:LazyLoading", true)
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("PartnerRolePartnerUser", b =>
                {
                    b.Property<int>("PartnerRolesId")
                        .HasColumnType("int");

                    b.Property<long>("PartnerUsersId")
                        .HasColumnType("bigint");

                    b.HasKey("PartnerRolesId", "PartnerUsersId");

                    b.HasIndex("PartnerUsersId");

                    b.ToTable("PartnerRolePartnerUser");
                });

            modelBuilder.Entity("PartnerUserSegmentation", b =>
                {
                    b.Property<int>("AlreadyFilledSegmentationsId")
                        .HasColumnType("int");

                    b.Property<long>("PartnerUsersThatHasFilledSegmentationId")
                        .HasColumnType("bigint");

                    b.HasKey("AlreadyFilledSegmentationsId", "PartnerUsersThatHasFilledSegmentationId");

                    b.HasIndex("PartnerUsersThatHasFilledSegmentationId");

                    b.ToTable("PartnerUserSegmentation");
                });

            modelBuilder.Entity("PartnerUserSegmentationItem", b =>
                {
                    b.Property<long>("CheckedSegmentationItemsId")
                        .HasColumnType("bigint");

                    b.Property<long>("PartnerUsersId")
                        .HasColumnType("bigint");

                    b.HasKey("CheckedSegmentationItemsId", "PartnerUsersId");

                    b.HasIndex("PartnerUsersId");

                    b.ToTable("PartnerUserSegmentationItem");
                });

            modelBuilder.Entity("PermissionRole", b =>
                {
                    b.Property<int>("PermissionsId")
                        .HasColumnType("int");

                    b.Property<int>("RolesId")
                        .HasColumnType("int");

                    b.HasKey("PermissionsId", "RolesId");

                    b.HasIndex("RolesId");

                    b.ToTable("PermissionRole");
                });

            modelBuilder.Entity("Playerty.Loyals.Business.Entities.Gender", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(70)
                        .HasColumnType("nvarchar(70)");

                    b.HasKey("Id");

                    b.ToTable("Genders");
                });

            modelBuilder.Entity("Playerty.Loyals.Business.Entities.Notification", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("Id"));

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasMaxLength(400)
                        .HasColumnType("nvarchar(400)");

                    b.Property<string>("Discriminator")
                        .IsRequired()
                        .HasMaxLength(21)
                        .HasColumnType("nvarchar(21)");

                    b.Property<string>("EmailBody")
                        .HasMaxLength(1000)
                        .HasColumnType("nvarchar(1000)");

                    b.Property<DateTime>("ModifiedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<int>("Version")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.ToTable("Notifications");

                    b.HasDiscriminator<string>("Discriminator").HasValue("Notification");

                    b.UseTphMappingStrategy();
                });

            modelBuilder.Entity("Playerty.Loyals.Business.Entities.NotificationUser", b =>
                {
                    b.Property<long>("NotificationsId")
                        .HasColumnType("bigint");

                    b.Property<long>("UsersId")
                        .HasColumnType("bigint");

                    b.Property<bool>("IsMarkedAsRead")
                        .HasColumnType("bit");

                    b.HasKey("NotificationsId", "UsersId");

                    b.HasIndex("UsersId");

                    b.ToTable("NotificationUser");
                });

            modelBuilder.Entity("Playerty.Loyals.Business.Entities.Partner", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("CreateUserEndpoint")
                        .HasMaxLength(1000)
                        .HasColumnType("nvarchar(1000)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("LoadPurchasesEndpoint")
                        .HasMaxLength(1000)
                        .HasColumnType("nvarchar(1000)");

                    b.Property<string>("LoadReversalsEndpoint")
                        .HasMaxLength(1000)
                        .HasColumnType("nvarchar(1000)");

                    b.Property<string>("LogoImage")
                        .HasMaxLength(1024)
                        .HasColumnType("nvarchar(1024)");

                    b.Property<DateTime>("ModifiedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<int>("PointsForTheFirstTimeBirthDateFill")
                        .HasColumnType("int");

                    b.Property<int>("PointsForTheFirstTimeGenderFill")
                        .HasColumnType("int");

                    b.Property<string>("PrimaryColor")
                        .HasMaxLength(7)
                        .HasColumnType("nvarchar(7)");

                    b.Property<string>("ProductsRecommendationEndpoint")
                        .HasMaxLength(1000)
                        .HasColumnType("nvarchar(1000)");

                    b.Property<string>("Slug")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<int?>("UpdatePointsInterval")
                        .HasColumnType("int");

                    b.Property<string>("UpdateUserGroupEndpoint")
                        .HasMaxLength(1000)
                        .HasColumnType("nvarchar(1000)");

                    b.Property<int>("Version")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("Slug")
                        .IsUnique();

                    b.ToTable("Partners");
                });

            modelBuilder.Entity("Playerty.Loyals.Business.Entities.PartnerNotificationPartnerUser", b =>
                {
                    b.Property<long>("PartnerNotificationsId")
                        .HasColumnType("bigint");

                    b.Property<long>("PartnerUsersId")
                        .HasColumnType("bigint");

                    b.Property<bool>("IsMarkedAsRead")
                        .HasColumnType("bit");

                    b.HasKey("PartnerNotificationsId", "PartnerUsersId");

                    b.HasIndex("PartnerUsersId");

                    b.ToTable("PartnerNotificationPartnerUser");
                });

            modelBuilder.Entity("Playerty.Loyals.Business.Entities.PartnerUser", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("Id"));

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<bool>("HasFilledBirthDateForTheFirstTime")
                        .HasColumnType("bit");

                    b.Property<bool>("HasFilledGenderForTheFirstTime")
                        .HasColumnType("bit");

                    b.Property<DateTime>("ModifiedAt")
                        .HasColumnType("datetime2");

                    b.Property<int?>("PartnerId")
                        .HasColumnType("int");

                    b.Property<int>("Points")
                        .HasColumnType("int");

                    b.Property<int?>("TierId")
                        .HasColumnType("int");

                    b.Property<long?>("UserId")
                        .HasColumnType("bigint");

                    b.Property<int>("Version")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("PartnerId");

                    b.HasIndex("TierId");

                    b.HasIndex("UserId");

                    b.ToTable("PartnerUsers");
                });

            modelBuilder.Entity("Playerty.Loyals.Business.Entities.Segmentation", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("Description")
                        .HasMaxLength(400)
                        .HasColumnType("nvarchar(400)");

                    b.Property<DateTime>("ModifiedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<int>("PartnerId")
                        .HasColumnType("int");

                    b.Property<int>("PointsForTheFirstTimeFill")
                        .HasColumnType("int");

                    b.Property<int>("Version")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("PartnerId");

                    b.ToTable("Segmentations");
                });

            modelBuilder.Entity("Playerty.Loyals.Business.Entities.SegmentationItem", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("Id"));

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("ModifiedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<int>("OrderNumber")
                        .HasColumnType("int");

                    b.Property<int>("SegmentationId")
                        .HasColumnType("int");

                    b.Property<int>("Version")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("SegmentationId");

                    b.ToTable("SegmentationItems");
                });

            modelBuilder.Entity("Playerty.Loyals.Business.Entities.Tier", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasMaxLength(400)
                        .HasColumnType("nvarchar(400)");

                    b.Property<DateTime>("ModifiedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<int?>("PartnerId")
                        .HasColumnType("int");

                    b.Property<int>("ValidFrom")
                        .HasColumnType("int");

                    b.Property<int>("ValidTo")
                        .HasColumnType("int");

                    b.Property<int>("Version")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("PartnerId");

                    b.ToTable("Tiers");
                });

            modelBuilder.Entity("Playerty.Loyals.Business.Entities.Transaction", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("Id"));

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<Guid>("Guid")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("ModifiedAt")
                        .HasColumnType("datetime2");

                    b.Property<int>("Points")
                        .HasColumnType("int");

                    b.Property<decimal>("Price")
                        .HasPrecision(16, 2)
                        .HasColumnType("decimal(16,2)");

                    b.Property<long>("UserId")
                        .HasColumnType("bigint");

                    b.Property<int>("Version")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("Transactions");
                });

            modelBuilder.Entity("Playerty.Loyals.Business.Entities.TransactionProduct", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("Id"));

                    b.Property<long>("ProductId")
                        .HasColumnType("bigint");

                    b.Property<long>("TransactionId")
                        .HasColumnType("bigint");

                    b.HasKey("Id");

                    b.HasIndex("TransactionId");

                    b.ToTable("TransactionProducts");
                });

            modelBuilder.Entity("Playerty.Loyals.Business.Entities.TransactionStatus", b =>
                {
                    b.Property<byte>("Id")
                        .HasColumnType("tinyint");

                    b.Property<string>("Code")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<long?>("TransactionId")
                        .HasColumnType("bigint");

                    b.HasKey("Id");

                    b.HasIndex("TransactionId");

                    b.ToTable("TransactionStatuses");
                });

            modelBuilder.Entity("Playerty.Loyals.Business.Entities.UserExtended", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("Id"));

                    b.Property<DateTime?>("BirthDate")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(70)
                        .HasColumnType("nvarchar(70)");

                    b.Property<int?>("GenderId")
                        .HasColumnType("int");

                    b.Property<bool>("HasLoggedInWithExternalProvider")
                        .HasColumnType("bit");

                    b.Property<DateTime>("ModifiedAt")
                        .HasColumnType("datetime2");

                    b.Property<int>("NumberOfFailedAttemptsInARow")
                        .HasColumnType("int");

                    b.Property<string>("Password")
                        .HasMaxLength(80)
                        .HasColumnType("nvarchar(80)");

                    b.Property<int>("Version")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("Email")
                        .IsUnique();

                    b.HasIndex("GenderId");

                    b.ToTable("Users");
                });

            modelBuilder.Entity("Soft.Generator.Security.Entities.Permission", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Code")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("Description")
                        .HasMaxLength(400)
                        .HasColumnType("nvarchar(400)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.HasKey("Id");

                    b.HasIndex("Code")
                        .IsUnique();

                    b.ToTable("Permissions");
                });

            modelBuilder.Entity("Soft.Generator.Security.Entities.Role", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("Description")
                        .HasMaxLength(400)
                        .HasColumnType("nvarchar(400)");

                    b.Property<string>("Discriminator")
                        .IsRequired()
                        .HasMaxLength(13)
                        .HasColumnType("nvarchar(13)");

                    b.Property<DateTime>("ModifiedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<int>("Version")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.ToTable("Roles");

                    b.HasDiscriminator<string>("Discriminator").HasValue("Role");

                    b.UseTphMappingStrategy();
                });

            modelBuilder.Entity("Soft.Generator.Security.Entities.RoleUser", b =>
                {
                    b.Property<int>("RolesId")
                        .HasColumnType("int");

                    b.Property<long>("UsersId")
                        .HasColumnType("bigint");

                    b.HasKey("RolesId", "UsersId");

                    b.HasIndex("UsersId");

                    b.ToTable("RoleUser");
                });

            modelBuilder.Entity("Playerty.Loyals.Business.Entities.PartnerNotification", b =>
                {
                    b.HasBaseType("Playerty.Loyals.Business.Entities.Notification");

                    b.Property<int>("PartnerId")
                        .HasColumnType("int");

                    b.HasIndex("PartnerId");

                    b.HasDiscriminator().HasValue("PartnerNotification");
                });

            modelBuilder.Entity("Playerty.Loyals.Business.Entities.PartnerRole", b =>
                {
                    b.HasBaseType("Soft.Generator.Security.Entities.Role");

                    b.Property<int>("PartnerId")
                        .HasColumnType("int");

                    b.HasIndex("PartnerId");

                    b.HasDiscriminator().HasValue("PartnerRole");
                });

            modelBuilder.Entity("PartnerRolePartnerUser", b =>
                {
                    b.HasOne("Playerty.Loyals.Business.Entities.PartnerRole", null)
                        .WithMany()
                        .HasForeignKey("PartnerRolesId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Playerty.Loyals.Business.Entities.PartnerUser", null)
                        .WithMany()
                        .HasForeignKey("PartnerUsersId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("PartnerUserSegmentation", b =>
                {
                    b.HasOne("Playerty.Loyals.Business.Entities.Segmentation", null)
                        .WithMany()
                        .HasForeignKey("AlreadyFilledSegmentationsId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Playerty.Loyals.Business.Entities.PartnerUser", null)
                        .WithMany()
                        .HasForeignKey("PartnerUsersThatHasFilledSegmentationId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("PartnerUserSegmentationItem", b =>
                {
                    b.HasOne("Playerty.Loyals.Business.Entities.SegmentationItem", null)
                        .WithMany()
                        .HasForeignKey("CheckedSegmentationItemsId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Playerty.Loyals.Business.Entities.PartnerUser", null)
                        .WithMany()
                        .HasForeignKey("PartnerUsersId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("PermissionRole", b =>
                {
                    b.HasOne("Soft.Generator.Security.Entities.Permission", null)
                        .WithMany()
                        .HasForeignKey("PermissionsId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Soft.Generator.Security.Entities.Role", null)
                        .WithMany()
                        .HasForeignKey("RolesId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Playerty.Loyals.Business.Entities.NotificationUser", b =>
                {
                    b.HasOne("Playerty.Loyals.Business.Entities.Notification", null)
                        .WithMany()
                        .HasForeignKey("NotificationsId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Playerty.Loyals.Business.Entities.UserExtended", null)
                        .WithMany()
                        .HasForeignKey("UsersId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Playerty.Loyals.Business.Entities.PartnerNotificationPartnerUser", b =>
                {
                    b.HasOne("Playerty.Loyals.Business.Entities.PartnerNotification", null)
                        .WithMany()
                        .HasForeignKey("PartnerNotificationsId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Playerty.Loyals.Business.Entities.PartnerUser", null)
                        .WithMany()
                        .HasForeignKey("PartnerUsersId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Playerty.Loyals.Business.Entities.PartnerUser", b =>
                {
                    b.HasOne("Playerty.Loyals.Business.Entities.Partner", "Partner")
                        .WithMany("Users")
                        .HasForeignKey("PartnerId");

                    b.HasOne("Playerty.Loyals.Business.Entities.Tier", "Tier")
                        .WithMany("PartnerUsers")
                        .HasForeignKey("TierId");

                    b.HasOne("Playerty.Loyals.Business.Entities.UserExtended", "User")
                        .WithMany("PartnerUsers")
                        .HasForeignKey("UserId");

                    b.Navigation("Partner");

                    b.Navigation("Tier");

                    b.Navigation("User");
                });

            modelBuilder.Entity("Playerty.Loyals.Business.Entities.Segmentation", b =>
                {
                    b.HasOne("Playerty.Loyals.Business.Entities.Partner", "Partner")
                        .WithMany()
                        .HasForeignKey("PartnerId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Partner");
                });

            modelBuilder.Entity("Playerty.Loyals.Business.Entities.SegmentationItem", b =>
                {
                    b.HasOne("Playerty.Loyals.Business.Entities.Segmentation", "Segmentation")
                        .WithMany("SegmentationItems")
                        .HasForeignKey("SegmentationId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Segmentation");
                });

            modelBuilder.Entity("Playerty.Loyals.Business.Entities.Tier", b =>
                {
                    b.HasOne("Playerty.Loyals.Business.Entities.Partner", "Partner")
                        .WithMany("Tiers")
                        .HasForeignKey("PartnerId");

                    b.Navigation("Partner");
                });

            modelBuilder.Entity("Playerty.Loyals.Business.Entities.Transaction", b =>
                {
                    b.HasOne("Playerty.Loyals.Business.Entities.UserExtended", "User")
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("Playerty.Loyals.Business.Entities.TransactionProduct", b =>
                {
                    b.HasOne("Playerty.Loyals.Business.Entities.Transaction", "Transaction")
                        .WithMany()
                        .HasForeignKey("TransactionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Transaction");
                });

            modelBuilder.Entity("Playerty.Loyals.Business.Entities.TransactionStatus", b =>
                {
                    b.HasOne("Playerty.Loyals.Business.Entities.Transaction", null)
                        .WithMany("Statuses")
                        .HasForeignKey("TransactionId");
                });

            modelBuilder.Entity("Playerty.Loyals.Business.Entities.UserExtended", b =>
                {
                    b.HasOne("Playerty.Loyals.Business.Entities.Gender", "Gender")
                        .WithMany()
                        .HasForeignKey("GenderId");

                    b.Navigation("Gender");
                });

            modelBuilder.Entity("Soft.Generator.Security.Entities.RoleUser", b =>
                {
                    b.HasOne("Soft.Generator.Security.Entities.Role", null)
                        .WithMany()
                        .HasForeignKey("RolesId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Playerty.Loyals.Business.Entities.UserExtended", null)
                        .WithMany()
                        .HasForeignKey("UsersId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Playerty.Loyals.Business.Entities.PartnerNotification", b =>
                {
                    b.HasOne("Playerty.Loyals.Business.Entities.Partner", "Partner")
                        .WithMany("PartnerNotifications")
                        .HasForeignKey("PartnerId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Partner");
                });

            modelBuilder.Entity("Playerty.Loyals.Business.Entities.PartnerRole", b =>
                {
                    b.HasOne("Playerty.Loyals.Business.Entities.Partner", "Partner")
                        .WithMany("PartnerRoles")
                        .HasForeignKey("PartnerId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Partner");
                });

            modelBuilder.Entity("Playerty.Loyals.Business.Entities.Partner", b =>
                {
                    b.Navigation("PartnerNotifications");

                    b.Navigation("PartnerRoles");

                    b.Navigation("Tiers");

                    b.Navigation("Users");
                });

            modelBuilder.Entity("Playerty.Loyals.Business.Entities.Segmentation", b =>
                {
                    b.Navigation("SegmentationItems");
                });

            modelBuilder.Entity("Playerty.Loyals.Business.Entities.Tier", b =>
                {
                    b.Navigation("PartnerUsers");
                });

            modelBuilder.Entity("Playerty.Loyals.Business.Entities.Transaction", b =>
                {
                    b.Navigation("Statuses");
                });

            modelBuilder.Entity("Playerty.Loyals.Business.Entities.UserExtended", b =>
                {
                    b.Navigation("PartnerUsers");
                });
#pragma warning restore 612, 618
        }
    }
}
