import { Injectable } from '@angular/core';
import { TranslocoService } from '@jsverse/transloco';

@Injectable({
  providedIn: 'root',
})
export class TranslateLabelsGeneratedService {

    constructor(
        private translocoService: TranslocoService
    ) {
    }

    translate(name: string): string
    {
        switch(name) 
        {
            case 'filters':
                return this.translocoService.translate('Filters');
            case 'first':
                return this.translocoService.translate('First');
            case 'rows':
                return this.translocoService.translate('Rows');
            case 'sortField':
                return this.translocoService.translate('SortField');
            case 'sortOrder':
                return this.translocoService.translate('SortOrder');
            case 'multiSortMeta':
                return this.translocoService.translate('MultiSortMeta');
            case 'additionalFilterIdInt':
                return this.translocoService.translate('AdditionalFilterIdInt');
            case 'additionalFilterIdLong':
                return this.translocoService.translate('AdditionalFilterIdLong');
            case 'selectedIds':
                return this.translocoService.translate('SelectedIds');
            case 'totalRecordsSelected':
                return this.translocoService.translate('TotalRecordsSelected');
            case 'id':
                return this.translocoService.translate('Id');
            case 'version':
                return this.translocoService.translate('Version');
            case 'createdAt':
                return this.translocoService.translate('CreatedAt');
            case 'modifiedAt':
                return this.translocoService.translate('ModifiedAt');
            case 'data':
                return this.translocoService.translate('Data');
            case 'totalRecords':
                return this.translocoService.translate('TotalRecords');
            case 'displayName':
                return this.translocoService.translate('DisplayName');
            case 'field':
                return this.translocoService.translate('Field');
            case 'order':
                return this.translocoService.translate('Order');
            case 'query':
                return this.translocoService.translate('Query');
            case 'value':
                return this.translocoService.translate('Value');
            case 'matchMode':
                return this.translocoService.translate('MatchMode');
            case 'operator':
                return this.translocoService.translate('Operator');
            case 'code':
                return this.translocoService.translate('Code');
            case 'additionalColumnHeaders':
                return this.translocoService.translate('AdditionalColumnHeaders');
            case 'additionalDataStartColumn':
                return this.translocoService.translate('AdditionalDataStartColumn');
            case 'dataSheetName':
                return this.translocoService.translate('DataSheetName');
            case 'dataSheetName2':
                return this.translocoService.translate('DataSheetName2');
            case 'dataStartRow':
                return this.translocoService.translate('DataStartRow');
            case 'dataStartColumn':
                return this.translocoService.translate('DataStartColumn');
            case 'createNewDataRows':
                return this.translocoService.translate('CreateNewDataRows');
            case 'user':
                return this.translocoService.translate('User');
            case 'userEmail':
                return this.translocoService.translate('UserEmail');
            case 'accessToken':
                return this.translocoService.translate('AccessToken');
            case 'token':
                return this.translocoService.translate('Token');
            case 'email':
                return this.translocoService.translate('Email');
            case 'refreshToken':
                return this.translocoService.translate('RefreshToken');
            case 'verificationCode':
                return this.translocoService.translate('VerificationCode');
            case 'browser':
                return this.translocoService.translate('Browser');
            case 'status':
                return this.translocoService.translate('Status');
            case 'message':
                return this.translocoService.translate('Message');
            case 'expireAt':
                return this.translocoService.translate('ExpireAt');
            case 'idToken':
                return this.translocoService.translate('IdToken');
            case 'ipAddress':
                return this.translocoService.translate('IpAddress');
            case 'tokenString':
                return this.translocoService.translate('TokenString');
            case 'selectedPermissionIds':
                return this.translocoService.translate('SelectedPermissionIds');
            case 'selectedUserIds':
                return this.translocoService.translate('SelectedUserIds');
            case 'roleDTO':
                return this.translocoService.translate('RoleDTO');
            case 'role':
                return this.translocoService.translate('Role');
            case 'permission':
                return this.translocoService.translate('Permission');
            case 'rolePermissionDTO':
                return this.translocoService.translate('RolePermissionDTO');
            case 'userRoleDTO':
                return this.translocoService.translate('UserRoleDTO');
            case 'name':
                return this.translocoService.translate('Name');
            case 'description':
                return this.translocoService.translate('Description');
            case 'nameLatin':
                return this.translocoService.translate('NameLatin');
            case 'descriptionLatin':
                return this.translocoService.translate('DescriptionLatin');
            case 'permissionDTO':
                return this.translocoService.translate('PermissionDTO');
            case 'selectedPartnerRoleIds':
                return this.translocoService.translate('SelectedPartnerRoleIds');
            case 'selectedSegmentationItemIds':
                return this.translocoService.translate('SelectedSegmentationItemIds');
            case 'userExtendedDTO':
                return this.translocoService.translate('UserExtendedDTO');
            case 'selectedRoleIds':
                return this.translocoService.translate('SelectedRoleIds');
            case 'partnerUserDTO':
                return this.translocoService.translate('PartnerUserDTO');
            case 'isMarkedAsRead':
                return this.translocoService.translate('IsMarkedAsRead');
            case 'tableFilter':
                return this.translocoService.translate('TableFilter');
            case 'unselectedIds':
                return this.translocoService.translate('UnselectedIds');
            case 'isAllSelected':
                return this.translocoService.translate('IsAllSelected');
            case 'notificationDTO':
                return this.translocoService.translate('NotificationDTO');
            case 'tierDTOList':
                return this.translocoService.translate('TierDTOList');
            case 'businessSystemTierDTOList':
                return this.translocoService.translate('BusinessSystemTierDTOList');
            case 'businessSystemTierDiscountProductGroupDTOList':
                return this.translocoService.translate('BusinessSystemTierDiscountProductGroupDTOList');
            case 'tierDTO':
                return this.translocoService.translate('TierDTO');
            case 'tierClientIndex':
                return this.translocoService.translate('TierClientIndex');
            case 'orderNumber':
                return this.translocoService.translate('OrderNumber');
            case 'businessSystem':
                return this.translocoService.translate('BusinessSystem');
            case 'tier':
                return this.translocoService.translate('Tier');
            case 'businessSystemTierDiscountProductGroupsDTOList':
                return this.translocoService.translate('BusinessSystemTierDiscountProductGroupsDTOList');
            case 'price':
                return this.translocoService.translate('Price');
            case 'category':
                return this.translocoService.translate('Category');
            case 'linkToWebsite':
                return this.translocoService.translate('LinkToWebsite');
            case 'pointsMultiplier':
                return this.translocoService.translate('PointsMultiplier');
            case 'productName':
                return this.translocoService.translate('ProductName');
            case 'productImageUrl':
                return this.translocoService.translate('ProductImageUrl');
            case 'productCategoryName':
                return this.translocoService.translate('ProductCategoryName');
            case 'productCategoryImageUrl':
                return this.translocoService.translate('ProductCategoryImageUrl');
            case 'boughtAt':
                return this.translocoService.translate('BoughtAt');
            case 'segmentationItemsDTO':
                return this.translocoService.translate('SegmentationItemsDTO');
            case 'segmentationDTO':
                return this.translocoService.translate('SegmentationDTO');
            case 'checked':
                return this.translocoService.translate('Checked');
            case 'segmentation':
                return this.translocoService.translate('Segmentation');
            case 'selectedPartnerUserIds':
                return this.translocoService.translate('SelectedPartnerUserIds');
            case 'partnerRoleDTO':
                return this.translocoService.translate('PartnerRoleDTO');
            case 'partnerNotificationDTO':
                return this.translocoService.translate('PartnerNotificationDTO');
            case 'businessSystemVersion':
                return this.translocoService.translate('BusinessSystemVersion');
            case 'fromDate':
                return this.translocoService.translate('FromDate');
            case 'toDate':
                return this.translocoService.translate('ToDate');
            case 'selectedForBusinessSystem':
                return this.translocoService.translate('SelectedForBusinessSystem');
            case 'businessSystemTierClientIndex':
                return this.translocoService.translate('BusinessSystemTierClientIndex');
            case 'businessSystemTier':
                return this.translocoService.translate('BusinessSystemTier');
            case 'discountProductGroup':
                return this.translocoService.translate('DiscountProductGroup');
            case 'discount':
                return this.translocoService.translate('Discount');
            case 'title':
                return this.translocoService.translate('Title');
            case 'emailBody':
                return this.translocoService.translate('EmailBody');
            case 'updatePointsStartDate':
                return this.translocoService.translate('UpdatePointsStartDate');
            case 'updatePointsInterval':
                return this.translocoService.translate('UpdatePointsInterval');
            case 'transactionCode':
                return this.translocoService.translate('TransactionCode');
            case 'businessSystemTierDTO':
                return this.translocoService.translate('BusinessSystemTierDTO');
            case 'genderDTO':
                return this.translocoService.translate('GenderDTO');
            case 'segmentationItemDTO':
                return this.translocoService.translate('SegmentationItemDTO');
            case 'partnerUserThatHasFilledSegmentation':
                return this.translocoService.translate('PartnerUserThatHasFilledSegmentation');
            case 'alreadyFilledSegmentation':
                return this.translocoService.translate('AlreadyFilledSegmentation');
            case 'partnerUserSegmentationDTO':
                return this.translocoService.translate('PartnerUserSegmentationDTO');
            case 'partnerNotification':
                return this.translocoService.translate('PartnerNotification');
            case 'partnerUser':
                return this.translocoService.translate('PartnerUser');
            case 'partnerUserPartnerNotificationDTO':
                return this.translocoService.translate('PartnerUserPartnerNotificationDTO');
            case 'discountProductGroupDTO':
                return this.translocoService.translate('DiscountProductGroupDTO');
            case 'hasLoggedInWithExternalProvider':
                return this.translocoService.translate('HasLoggedInWithExternalProvider');
            case 'isDisabled':
                return this.translocoService.translate('IsDisabled');
            case 'birthDate':
                return this.translocoService.translate('BirthDate');
            case 'gender':
                return this.translocoService.translate('Gender');
            case 'notification':
                return this.translocoService.translate('Notification');
            case 'userNotificationDTO':
                return this.translocoService.translate('UserNotificationDTO');
            case 'points':
                return this.translocoService.translate('Points');
            case 'transactionDTO':
                return this.translocoService.translate('TransactionDTO');
            case 'partner':
                return this.translocoService.translate('Partner');
            case 'partnerRole':
                return this.translocoService.translate('PartnerRole');
            case 'partnerPermission':
                return this.translocoService.translate('PartnerPermission');
            case 'partnerRolePartnerPermissionDTO':
                return this.translocoService.translate('PartnerRolePartnerPermissionDTO');
            case 'checkedSegmentationItems':
                return this.translocoService.translate('CheckedSegmentationItems');
            case 'businessSystemTierDiscountProductGroupDTO':
                return this.translocoService.translate('BusinessSystemTierDiscountProductGroupDTO');
            case 'getTransactionsEndpoint':
                return this.translocoService.translate('GetTransactionsEndpoint');
            case 'getDiscountCategoriesEndpoint':
                return this.translocoService.translate('GetDiscountCategoriesEndpoint');
            case 'createUserEndpoint':
                return this.translocoService.translate('CreateUserEndpoint');
            case 'updateUserGroupEndpoint':
                return this.translocoService.translate('UpdateUserGroupEndpoint');
            case 'updatePointsScheduledTaskIsPaused':
                return this.translocoService.translate('UpdatePointsScheduledTaskIsPaused');
            case 'businessSystemDTO':
                return this.translocoService.translate('BusinessSystemDTO');
            case 'partnerUserPartnerRoleDTO':
                return this.translocoService.translate('PartnerUserPartnerRoleDTO');
            case 'transactionsFrom':
                return this.translocoService.translate('TransactionsFrom');
            case 'transactionsTo':
                return this.translocoService.translate('TransactionsTo');
            case 'isManual':
                return this.translocoService.translate('IsManual');
            case 'businessSystemUpdatePointsScheduledTaskDTO':
                return this.translocoService.translate('BusinessSystemUpdatePointsScheduledTaskDTO');
            case 'slug':
                return this.translocoService.translate('Slug');
            case 'logoImageData':
                return this.translocoService.translate('LogoImageData');
            case 'logoImage':
                return this.translocoService.translate('LogoImage');
            case 'primaryColor':
                return this.translocoService.translate('PrimaryColor');
            case 'productsRecommendationEndpoint':
                return this.translocoService.translate('ProductsRecommendationEndpoint');
            case 'partnerDTO':
                return this.translocoService.translate('PartnerDTO');
            case 'checkedSegmentationItem':
                return this.translocoService.translate('CheckedSegmentationItem');
            case 'partnerUserSegmentationItemDTO':
                return this.translocoService.translate('PartnerUserSegmentationItemDTO');
            case 'partnerPermissionDTO':
                return this.translocoService.translate('PartnerPermissionDTO');
            case 'validFrom':
                return this.translocoService.translate('ValidFrom');
            case 'validTo':
                return this.translocoService.translate('ValidTo');
            case 'businessSystemTiersDTOList':
                return this.translocoService.translate('BusinessSystemTiersDTOList');
            case 'pointsForTheFirstTimeFill':
                return this.translocoService.translate('PointsForTheFirstTimeFill');
            default:
                return null;
        }
    }
}

