//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PlayertyLoyals.Shared.Terms {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class TermsGenerated {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal TermsGenerated() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("PlayertyLoyals.Shared.Terms.TermsGenerated", typeof(TermsGenerated).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        public static string AlreadyFilledSegmentation {
            get {
                return ResourceManager.GetString("AlreadyFilledSegmentation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        public static string AlreadyFilledSegmentations {
            get {
                return ResourceManager.GetString("AlreadyFilledSegmentations", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        public static string BirthDate {
            get {
                return ResourceManager.GetString("BirthDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        public static string BoughtAt {
            get {
                return ResourceManager.GetString("BoughtAt", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        public static string BusinessObject {
            get {
                return ResourceManager.GetString("BusinessObject", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        public static string BusinessObjectExcelExportName {
            get {
                return ResourceManager.GetString("BusinessObjectExcelExportName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        public static string BusinessObjectList {
            get {
                return ResourceManager.GetString("BusinessObjectList", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        public static string BusinessSystem {
            get {
                return ResourceManager.GetString("BusinessSystem", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        public static string BusinessSystemExcelExportName {
            get {
                return ResourceManager.GetString("BusinessSystemExcelExportName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        public static string BusinessSystemList {
            get {
                return ResourceManager.GetString("BusinessSystemList", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        public static string BusinessSystems {
            get {
                return ResourceManager.GetString("BusinessSystems", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        public static string BusinessSystemTier {
            get {
                return ResourceManager.GetString("BusinessSystemTier", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        public static string BusinessSystemTierDiscountProductGroup {
            get {
                return ResourceManager.GetString("BusinessSystemTierDiscountProductGroup", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        public static string BusinessSystemTierDiscountProductGroupExcelExportName {
            get {
                return ResourceManager.GetString("BusinessSystemTierDiscountProductGroupExcelExportName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        public static string BusinessSystemTierDiscountProductGroupList {
            get {
                return ResourceManager.GetString("BusinessSystemTierDiscountProductGroupList", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        public static string BusinessSystemTierDiscountProductGroups {
            get {
                return ResourceManager.GetString("BusinessSystemTierDiscountProductGroups", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        public static string BusinessSystemTierExcelExportName {
            get {
                return ResourceManager.GetString("BusinessSystemTierExcelExportName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        public static string BusinessSystemTierList {
            get {
                return ResourceManager.GetString("BusinessSystemTierList", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        public static string BusinessSystemTiers {
            get {
                return ResourceManager.GetString("BusinessSystemTiers", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        public static string BusinessSystemUpdatePointsScheduledTask {
            get {
                return ResourceManager.GetString("BusinessSystemUpdatePointsScheduledTask", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        public static string BusinessSystemUpdatePointsScheduledTaskExcelExportName {
            get {
                return ResourceManager.GetString("BusinessSystemUpdatePointsScheduledTaskExcelExportName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        public static string BusinessSystemUpdatePointsScheduledTaskList {
            get {
                return ResourceManager.GetString("BusinessSystemUpdatePointsScheduledTaskList", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        public static string BusinessSystemUpdatePointsScheduledTasks {
            get {
                return ResourceManager.GetString("BusinessSystemUpdatePointsScheduledTasks", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        public static string CheckedSegmentationItem {
            get {
                return ResourceManager.GetString("CheckedSegmentationItem", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        public static string CheckedSegmentationItems {
            get {
                return ResourceManager.GetString("CheckedSegmentationItems", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        public static string Code {
            get {
                return ResourceManager.GetString("Code", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        public static string CreatedAt {
            get {
                return ResourceManager.GetString("CreatedAt", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        public static string CreateUserEndpoint {
            get {
                return ResourceManager.GetString("CreateUserEndpoint", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        public static string Description {
            get {
                return ResourceManager.GetString("Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        public static string DescriptionLatin {
            get {
                return ResourceManager.GetString("DescriptionLatin", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        public static string Discount {
            get {
                return ResourceManager.GetString("Discount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        public static string DiscountProductGroup {
            get {
                return ResourceManager.GetString("DiscountProductGroup", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        public static string DiscountProductGroupExcelExportName {
            get {
                return ResourceManager.GetString("DiscountProductGroupExcelExportName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        public static string DiscountProductGroupList {
            get {
                return ResourceManager.GetString("DiscountProductGroupList", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        public static string DiscountProductGroups {
            get {
                return ResourceManager.GetString("DiscountProductGroups", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        public static string Email {
            get {
                return ResourceManager.GetString("Email", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        public static string EmailBody {
            get {
                return ResourceManager.GetString("EmailBody", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        public static string Gender {
            get {
                return ResourceManager.GetString("Gender", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        public static string GenderExcelExportName {
            get {
                return ResourceManager.GetString("GenderExcelExportName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        public static string GenderList {
            get {
                return ResourceManager.GetString("GenderList", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        public static string GetDiscountCategoriesEndpoint {
            get {
                return ResourceManager.GetString("GetDiscountCategoriesEndpoint", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        public static string GetTransactionsEndpoint {
            get {
                return ResourceManager.GetString("GetTransactionsEndpoint", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        public static string HasLoggedInWithExternalProvider {
            get {
                return ResourceManager.GetString("HasLoggedInWithExternalProvider", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        public static string Id {
            get {
                return ResourceManager.GetString("Id", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        public static string IsDisabled {
            get {
                return ResourceManager.GetString("IsDisabled", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        public static string IsManual {
            get {
                return ResourceManager.GetString("IsManual", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        public static string IsMarkedAsRead {
            get {
                return ResourceManager.GetString("IsMarkedAsRead", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        public static string LogoImage {
            get {
                return ResourceManager.GetString("LogoImage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        public static string ModifiedAt {
            get {
                return ResourceManager.GetString("ModifiedAt", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        public static string Name {
            get {
                return ResourceManager.GetString("Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        public static string NameLatin {
            get {
                return ResourceManager.GetString("NameLatin", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        public static string Notification {
            get {
                return ResourceManager.GetString("Notification", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        public static string NotificationExcelExportName {
            get {
                return ResourceManager.GetString("NotificationExcelExportName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        public static string NotificationList {
            get {
                return ResourceManager.GetString("NotificationList", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        public static string Notifications {
            get {
                return ResourceManager.GetString("Notifications", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        public static string OrderNumber {
            get {
                return ResourceManager.GetString("OrderNumber", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        public static string Partner {
            get {
                return ResourceManager.GetString("Partner", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        public static string PartnerExcelExportName {
            get {
                return ResourceManager.GetString("PartnerExcelExportName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        public static string PartnerList {
            get {
                return ResourceManager.GetString("PartnerList", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        public static string PartnerNotification {
            get {
                return ResourceManager.GetString("PartnerNotification", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        public static string PartnerNotificationExcelExportName {
            get {
                return ResourceManager.GetString("PartnerNotificationExcelExportName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        public static string PartnerNotificationList {
            get {
                return ResourceManager.GetString("PartnerNotificationList", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        public static string PartnerNotifications {
            get {
                return ResourceManager.GetString("PartnerNotifications", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        public static string PartnerPermission {
            get {
                return ResourceManager.GetString("PartnerPermission", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        public static string PartnerPermissionExcelExportName {
            get {
                return ResourceManager.GetString("PartnerPermissionExcelExportName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        public static string PartnerPermissionList {
            get {
                return ResourceManager.GetString("PartnerPermissionList", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        public static string PartnerPermissions {
            get {
                return ResourceManager.GetString("PartnerPermissions", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        public static string PartnerRole {
            get {
                return ResourceManager.GetString("PartnerRole", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        public static string PartnerRoleExcelExportName {
            get {
                return ResourceManager.GetString("PartnerRoleExcelExportName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        public static string PartnerRoleList {
            get {
                return ResourceManager.GetString("PartnerRoleList", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        public static string PartnerRolePartnerPermission {
            get {
                return ResourceManager.GetString("PartnerRolePartnerPermission", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        public static string PartnerRolePartnerPermissionExcelExportName {
            get {
                return ResourceManager.GetString("PartnerRolePartnerPermissionExcelExportName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        public static string PartnerRolePartnerPermissionList {
            get {
                return ResourceManager.GetString("PartnerRolePartnerPermissionList", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        public static string PartnerRoles {
            get {
                return ResourceManager.GetString("PartnerRoles", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        public static string PartnerUser {
            get {
                return ResourceManager.GetString("PartnerUser", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        public static string PartnerUserExcelExportName {
            get {
                return ResourceManager.GetString("PartnerUserExcelExportName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        public static string PartnerUserList {
            get {
                return ResourceManager.GetString("PartnerUserList", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        public static string PartnerUserPartnerNotification {
            get {
                return ResourceManager.GetString("PartnerUserPartnerNotification", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        public static string PartnerUserPartnerNotificationExcelExportName {
            get {
                return ResourceManager.GetString("PartnerUserPartnerNotificationExcelExportName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        public static string PartnerUserPartnerNotificationList {
            get {
                return ResourceManager.GetString("PartnerUserPartnerNotificationList", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        public static string PartnerUserPartnerRole {
            get {
                return ResourceManager.GetString("PartnerUserPartnerRole", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        public static string PartnerUserPartnerRoleExcelExportName {
            get {
                return ResourceManager.GetString("PartnerUserPartnerRoleExcelExportName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        public static string PartnerUserPartnerRoleList {
            get {
                return ResourceManager.GetString("PartnerUserPartnerRoleList", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        public static string PartnerUsers {
            get {
                return ResourceManager.GetString("PartnerUsers", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        public static string PartnerUserSegmentation {
            get {
                return ResourceManager.GetString("PartnerUserSegmentation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        public static string PartnerUserSegmentationExcelExportName {
            get {
                return ResourceManager.GetString("PartnerUserSegmentationExcelExportName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        public static string PartnerUserSegmentationItem {
            get {
                return ResourceManager.GetString("PartnerUserSegmentationItem", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        public static string PartnerUserSegmentationItemExcelExportName {
            get {
                return ResourceManager.GetString("PartnerUserSegmentationItemExcelExportName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        public static string PartnerUserSegmentationItemList {
            get {
                return ResourceManager.GetString("PartnerUserSegmentationItemList", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        public static string PartnerUserSegmentationList {
            get {
                return ResourceManager.GetString("PartnerUserSegmentationList", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        public static string PartnerUsersThatHasFilledSegmentation {
            get {
                return ResourceManager.GetString("PartnerUsersThatHasFilledSegmentation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        public static string PartnerUserThatHasFilledSegmentation {
            get {
                return ResourceManager.GetString("PartnerUserThatHasFilledSegmentation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        public static string Permission {
            get {
                return ResourceManager.GetString("Permission", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        public static string PermissionExcelExportName {
            get {
                return ResourceManager.GetString("PermissionExcelExportName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        public static string PermissionList {
            get {
                return ResourceManager.GetString("PermissionList", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        public static string Permissions {
            get {
                return ResourceManager.GetString("Permissions", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        public static string Points {
            get {
                return ResourceManager.GetString("Points", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        public static string PointsForTheFirstTimeFill {
            get {
                return ResourceManager.GetString("PointsForTheFirstTimeFill", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        public static string PointsMultiplier {
            get {
                return ResourceManager.GetString("PointsMultiplier", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        public static string Price {
            get {
                return ResourceManager.GetString("Price", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        public static string PrimaryColor {
            get {
                return ResourceManager.GetString("PrimaryColor", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        public static string ProductCategoryImageUrl {
            get {
                return ResourceManager.GetString("ProductCategoryImageUrl", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        public static string ProductCategoryName {
            get {
                return ResourceManager.GetString("ProductCategoryName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        public static string ProductImageUrl {
            get {
                return ResourceManager.GetString("ProductImageUrl", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        public static string ProductName {
            get {
                return ResourceManager.GetString("ProductName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        public static string ProductsRecommendationEndpoint {
            get {
                return ResourceManager.GetString("ProductsRecommendationEndpoint", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        public static string ReadonlyObject {
            get {
                return ResourceManager.GetString("ReadonlyObject", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        public static string ReadonlyObjectExcelExportName {
            get {
                return ResourceManager.GetString("ReadonlyObjectExcelExportName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        public static string ReadonlyObjectList {
            get {
                return ResourceManager.GetString("ReadonlyObjectList", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        public static string Role {
            get {
                return ResourceManager.GetString("Role", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        public static string RoleExcelExportName {
            get {
                return ResourceManager.GetString("RoleExcelExportName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        public static string RoleId {
            get {
                return ResourceManager.GetString("RoleId", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        public static string RoleList {
            get {
                return ResourceManager.GetString("RoleList", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        public static string RolePermission {
            get {
                return ResourceManager.GetString("RolePermission", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        public static string RolePermissionExcelExportName {
            get {
                return ResourceManager.GetString("RolePermissionExcelExportName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        public static string RolePermissionList {
            get {
                return ResourceManager.GetString("RolePermissionList", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        public static string Roles {
            get {
                return ResourceManager.GetString("Roles", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        public static string ScheduledTaskType {
            get {
                return ResourceManager.GetString("ScheduledTaskType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        public static string ScheduledTaskTypeExcelExportName {
            get {
                return ResourceManager.GetString("ScheduledTaskTypeExcelExportName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        public static string ScheduledTaskTypeList {
            get {
                return ResourceManager.GetString("ScheduledTaskTypeList", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        public static string Segmentation {
            get {
                return ResourceManager.GetString("Segmentation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        public static string SegmentationExcelExportName {
            get {
                return ResourceManager.GetString("SegmentationExcelExportName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        public static string SegmentationItem {
            get {
                return ResourceManager.GetString("SegmentationItem", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        public static string SegmentationItemExcelExportName {
            get {
                return ResourceManager.GetString("SegmentationItemExcelExportName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        public static string SegmentationItemList {
            get {
                return ResourceManager.GetString("SegmentationItemList", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        public static string SegmentationItems {
            get {
                return ResourceManager.GetString("SegmentationItems", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        public static string SegmentationList {
            get {
                return ResourceManager.GetString("SegmentationList", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        public static string Segmentations {
            get {
                return ResourceManager.GetString("Segmentations", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        public static string Slug {
            get {
                return ResourceManager.GetString("Slug", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        public static string Tier {
            get {
                return ResourceManager.GetString("Tier", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        public static string TierExcelExportName {
            get {
                return ResourceManager.GetString("TierExcelExportName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        public static string TierList {
            get {
                return ResourceManager.GetString("TierList", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        public static string Tiers {
            get {
                return ResourceManager.GetString("Tiers", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        public static string Title {
            get {
                return ResourceManager.GetString("Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        public static string Transaction {
            get {
                return ResourceManager.GetString("Transaction", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        public static string TransactionExcelExportName {
            get {
                return ResourceManager.GetString("TransactionExcelExportName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        public static string TransactionList {
            get {
                return ResourceManager.GetString("TransactionList", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        public static string Transactions {
            get {
                return ResourceManager.GetString("Transactions", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        public static string TransactionsFrom {
            get {
                return ResourceManager.GetString("TransactionsFrom", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        public static string TransactionsTo {
            get {
                return ResourceManager.GetString("TransactionsTo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        public static string UpdatePointsInterval {
            get {
                return ResourceManager.GetString("UpdatePointsInterval", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        public static string UpdatePointsScheduledTaskIsPaused {
            get {
                return ResourceManager.GetString("UpdatePointsScheduledTaskIsPaused", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        public static string UpdatePointsStartDate {
            get {
                return ResourceManager.GetString("UpdatePointsStartDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        public static string UpdateUserGroupEndpoint {
            get {
                return ResourceManager.GetString("UpdateUserGroupEndpoint", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        public static string User {
            get {
                return ResourceManager.GetString("User", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        public static string UserExtended {
            get {
                return ResourceManager.GetString("UserExtended", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        public static string UserExtendedExcelExportName {
            get {
                return ResourceManager.GetString("UserExtendedExcelExportName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        public static string UserExtendedList {
            get {
                return ResourceManager.GetString("UserExtendedList", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        public static string UserId {
            get {
                return ResourceManager.GetString("UserId", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        public static string UserNotification {
            get {
                return ResourceManager.GetString("UserNotification", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        public static string UserNotificationExcelExportName {
            get {
                return ResourceManager.GetString("UserNotificationExcelExportName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        public static string UserNotificationList {
            get {
                return ResourceManager.GetString("UserNotificationList", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        public static string UserRole {
            get {
                return ResourceManager.GetString("UserRole", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        public static string UserRoleExcelExportName {
            get {
                return ResourceManager.GetString("UserRoleExcelExportName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        public static string UserRoleList {
            get {
                return ResourceManager.GetString("UserRoleList", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        public static string Users {
            get {
                return ResourceManager.GetString("Users", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        public static string ValidFrom {
            get {
                return ResourceManager.GetString("ValidFrom", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        public static string ValidTo {
            get {
                return ResourceManager.GetString("ValidTo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        public static string Version {
            get {
                return ResourceManager.GetString("Version", resourceCulture);
            }
        }
    }
}
